### ISSUE TITLE
Can't place minecart on rail

### ISSUE THREAD

**Issue by EoinKanro** [JDKDigital/everythingcopper#18]
Hi!
I'm getting the error when I'm trying to place a minecart on a rail

And I don't really understand if it's a problem of everythingcopper or puzzlelib / something else from the stacktrace

Can you please help?

[23:19:18] [Server thread/ERROR] [minecraft/ServerPacketListener]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@3b4b9d3e, suppressing error
java.lang.IllegalArgumentException: Data value id is too big with 17! (Max is 14)
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.syncher.SynchedEntityData$Builder.define(SynchedEntityData.java:153) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:mixin,re:classloading}
        at TRANSFORMER/everythingcopper@1.21.1-2.3.8/cy.jdkdigital.everythingcopper.common.entity.CopperMinecart.defineSynchedData(CopperMinecart.java:34) ~[everythingcopper-1.21.1-2.3.8.jar%23254!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Entity.<init>(Entity.java:266) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.vehicle.VehicleEntity.<init>(VehicleEntity.java:24) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.vehicle.AbstractMinecart.<init>(AbstractMinecart.java:90) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:mixin,re:classloading,pl:mixin:APP:puzzleslib.common.mixins.json:AbstractMinecartMixin from mod puzzleslib,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.vehicle.AbstractMinecart.<init>(AbstractMinecart.java:95) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:mixin,re:classloading,pl:mixin:APP:puzzleslib.common.mixins.json:AbstractMinecartMixin from mod puzzleslib,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.vehicle.Minecart.<init>(Minecart.java:17) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:computing_frames,re:classloading}
        at TRANSFORMER/everythingcopper@1.21.1-2.3.8/cy.jdkdigital.everythingcopper.common.entity.CopperMinecart.<init>(CopperMinecart.java:23) ~[everythingcopper-1.21.1-2.3.8.jar%23254!/:?] {re:classloading}
        at TRANSFORMER/everythingcopper@1.21.1-2.3.8/cy.jdkdigital.everythingcopper.common.entity.CopperMinecart.createMinecart(CopperMinecart.java:92) ~[everythingcopper-1.21.1-2.3.8.jar%23254!/:?] {re:classloading}
        at TRANSFORMER/everythingcopper@1.21.1-2.3.8/cy.jdkdigital.everythingcopper.common.item.CopperMinecartItem.useOn(CopperMinecartItem.java:41) ~[everythingcopper-1.21.1-2.3.8.jar%23254!/:?] {re:classloading}
        at TRANSFORMER/neoforge@21.1.68/net.neoforged.neoforge.common.CommonHooks.onPlaceItemIntoWorld(CommonHooks.java:614) ~[neoforge-21.1.68-universal.jar%23224!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.ItemStack.useOn(ItemStack.java:360) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:deeperdarker.mixins.json:ItemStackMixin from mod deeperdarker,pl:mixin:APP:glitchcore.mixins.json:MixinItemStack from mod glitchcore,pl:mixin:APP:bettercombat.mixins.json:ItemStackMixin from mod bettercombat,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:386) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:the_bumblezone-common.mixins.json:gameplay.ServerPlayerGameModeMixin from mod the_bumblezone,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1122) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:features.misc.ServerGamePacketListenerImplMixin from mod servercore,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.ServerGamePacketListenerImplMixin from mod the_bumblezone,pl:mixin:APP:bettercombat.mixins.json:ServerPlayNetworkHandlerMixin from mod bettercombat,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ServerPlayNetHandlerAccess from mod immersiveengineering,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:42) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:10) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:27) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:mixin,re:computing_frames,re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:872) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:170) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:855) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:849) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:111) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:825) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:712) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}

**Comment by JaisDK** [comment]
I guess they don't work on 1.21, I'll look into it
